<a href="https://www.kaggle.com/code/ramanask/notebook30cc0f4f7e?scriptVersionId=136836881" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/hand-written-digit-predicition/Untitled1.ipynb


In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt

In [5]:
from sklearn.datasets import load_digits

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [6]:
from sklearn.model_selection import train_test_split

In [7]:
from sklearn.ensemble import RandomForestClassifier

In [8]:
from sklearn.metrics import confusion_matrix,classification_report

In [9]:
df=load_digits()

DATA PREPROCESSING

In [10]:
df.images.shape

(1797, 8, 8)

In [11]:
df.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [12]:
df.images[0].shape

(8, 8)

In [13]:
len(df.images)

1797

In [14]:
n_samples=len(df.images)

In [15]:
data=df.images.reshape((n_samples,-1))

In [16]:
data[0].shape

(64,)

In [17]:
data.shape

(1797, 64)

In [18]:
data.min()

0.0

In [19]:
data.max()

16.0

In [20]:
data=data/16

In [21]:
data.min()

0.0

In [22]:
data.max()

1.0

In [23]:
data[0]

array([0.    , 0.    , 0.3125, 0.8125, 0.5625, 0.0625, 0.    , 0.    ,
       0.    , 0.    , 0.8125, 0.9375, 0.625 , 0.9375, 0.3125, 0.    ,
       0.    , 0.1875, 0.9375, 0.125 , 0.    , 0.6875, 0.5   , 0.    ,
       0.    , 0.25  , 0.75  , 0.    , 0.    , 0.5   , 0.5   , 0.    ,
       0.    , 0.3125, 0.5   , 0.    , 0.    , 0.5625, 0.5   , 0.    ,
       0.    , 0.25  , 0.6875, 0.    , 0.0625, 0.75  , 0.4375, 0.    ,
       0.    , 0.125 , 0.875 , 0.3125, 0.625 , 0.75  , 0.    , 0.    ,
       0.    , 0.    , 0.375 , 0.8125, 0.625 , 0.    , 0.    , 0.    ])

TRIAN TEST SPLIT DATA

In [24]:
x_train,x_test,y_train,y_test=train_test_split(data,df.target,test_size=0.3)

In [25]:
x_train.shape,y_test.shape,y_train.shape,x_test.shape,y_train.shape,y_train.shape

((1257, 64), (540,), (1257,), (540, 64), (1257,), (1257,))

RANDOM FOREST MODEL

In [26]:
rf=RandomForestClassifier()

In [27]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [28]:
y_pred=rf.predict(x_test)

In [29]:
y_pred

array([5, 5, 2, 3, 6, 8, 7, 4, 8, 2, 1, 2, 2, 3, 7, 0, 7, 6, 8, 4, 3, 5,
       4, 6, 3, 1, 5, 8, 7, 6, 0, 8, 5, 2, 6, 1, 6, 1, 9, 4, 0, 8, 5, 7,
       5, 1, 3, 6, 9, 8, 9, 7, 9, 6, 3, 0, 2, 1, 9, 9, 3, 9, 6, 1, 2, 5,
       1, 6, 4, 7, 2, 7, 9, 9, 7, 7, 2, 4, 3, 2, 3, 4, 8, 9, 3, 5, 5, 0,
       8, 4, 0, 6, 2, 2, 3, 0, 1, 4, 3, 6, 0, 2, 0, 2, 8, 6, 7, 4, 8, 6,
       1, 0, 1, 3, 0, 5, 8, 7, 8, 5, 3, 2, 9, 8, 4, 4, 0, 7, 1, 0, 7, 6,
       3, 9, 2, 1, 0, 6, 7, 7, 5, 3, 1, 0, 6, 8, 3, 1, 1, 6, 1, 2, 8, 2,
       1, 3, 5, 8, 4, 3, 0, 3, 3, 9, 6, 1, 5, 6, 1, 3, 5, 7, 2, 0, 4, 4,
       7, 6, 1, 7, 6, 3, 2, 7, 0, 1, 6, 1, 9, 3, 7, 0, 3, 4, 8, 7, 2, 4,
       5, 0, 5, 4, 6, 4, 2, 4, 1, 3, 6, 5, 8, 5, 0, 4, 5, 2, 0, 6, 5, 0,
       1, 1, 7, 5, 5, 1, 1, 4, 0, 9, 2, 5, 7, 5, 7, 5, 6, 4, 4, 9, 3, 5,
       7, 1, 5, 6, 9, 9, 8, 7, 0, 0, 1, 0, 5, 2, 0, 0, 8, 3, 2, 3, 4, 6,
       4, 8, 1, 1, 2, 9, 1, 9, 6, 1, 7, 0, 3, 8, 6, 9, 0, 9, 0, 0, 1, 8,
       4, 1, 5, 9, 6, 5, 3, 2, 7, 4, 2, 8, 3, 4, 6,

In [30]:
confusion_matrix(y_test,y_pred)

array([[59,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 59,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 49,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 58,  0,  0,  0,  1,  1,  0],
       [ 0,  0,  0,  0, 54,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  1, 55,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0, 52,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 52,  0,  0],
       [ 0,  1,  1,  0,  0,  0,  0,  1, 44,  0],
       [ 0,  0,  0,  2,  1,  1,  0,  0,  1, 46]])

In [31]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        59
           1       0.98      1.00      0.99        59
           2       0.98      1.00      0.99        49
           3       0.97      0.97      0.97        60
           4       0.96      1.00      0.98        54
           5       0.98      0.98      0.98        56
           6       1.00      0.98      0.99        53
           7       0.96      1.00      0.98        52
           8       0.96      0.94      0.95        47
           9       1.00      0.90      0.95        51

    accuracy                           0.98       540
   macro avg       0.98      0.98      0.98       540
weighted avg       0.98      0.98      0.98       540

